// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.thesarvo.guide.client.view.res;
import com.google.gwt.resources.client.CssResource;
public interface GuideStyle extends CssResource {
  
	String transparentDiv();
	String legendClimbs();
	String legendTable();
	String legendDiv();
	String legendNameCol();
	String legendSmallCol();
	String legendNameDiv();
	String legendTitle();
	String legendFooter();
	
	String medText();
	
	String climb();
  
  String climbfa();
  String climbnum();
  String climbname();
  String climbgrade();
  String climblength();
  String climbextra();
  String climbstars();
  
  String climbmultitext();
  String climbmultilabel();
  
  
  String climbtext();
  
  String editing();
  
  String editMode();
  
  String faTextBox();
  
  String header1();
  
  String heading1();
  
  String heading2();
  
  String heading3();
  
  String smallText();
  
  String text();
  
  String textArea();
  
  String tsleftcell();
  
  String tssubcont();
  
  String tssubhead();
  
  String tstr();

  String intro();
  
  String access();
  
  String description();
  
  String savingPopup();
  
  String displayNone();
  
  String guideView();
  
  String image();
  
  String gpsCell();
}


