// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.thesarvo.xphone.client.ui.theme;
import com.google.gwt.resources.client.CssResource;
public interface ThemeStyle extends CssResource {
  
  String active();
  
  String add();
  
  String arrow();
  
  String back();
  
  String bigbanner();
  
  @ClassName("black-translucent")
  String blackTranslucent();
  
  String blueButton();
  
  String button();
  
  String cancel();
  
  String counter();
  
  String edgetoedge();
  
  String error();
  
  String form();
  
  String grayButton();
  
  String img();
  
  String individual();
  
  String info();
  
  String landscape();
  
  String leftButton();
  
  String metal();
  
  String minibanner();
  
  String plastic();
  
  String toggle();
  
  String toolbar();
  
  String whiteButton();
  
  String expandoLabel();
  String expandoContent();
  String expandoLabelOpened();
  String expandoLabelClosed();
  
}

