// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.thesarvo.xphone.client.ui.theme;
import com.google.gwt.resources.client.CssResource;
public interface XphoneStyle extends CssResource {
  
  @ClassName("black-translucent")
  String blackTranslucent();
  
  String cube();
  
  String current();
  
  String dissolve();
  
  String fade();
  
  String flip();
  
  String fullscreen();
  
  String in();
  
  String landscape();
  
  String out();
  
  String pop();
  
  String reverse();
  
  String selectable();
  
  String slide();
  
  String slideup();
  
  String swap();
  
  String visible();
  String notvisible();
  String view();
  String viewContainer();
}

